# 2020.03.20 Ver.16
version: 2.1
orbs:
  slack: circleci/slack@3.3.0
executors:
  go-executor:
    docker:
      - image: circleci/golang:1.13.4
  terraform-executor:
    docker:
      - image: hashicorp/terraform:0.12.23


jobs:
  start-workflow:
    docker:
      - image: "circleci/python:2.7"
    steps:
      - run:
          name: Workflow Start job
          command: |
            echo "Workflow Start!"
            echo ${CIRCLE_BUILD_URL}
            echo ${CIRCLE_COMPARE_URL}
            echo ${CIRCLE_JOB}
  aws-vpc:
    executor: terraform-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd ~/project/vpc
            terraform init -input=false
            terraform apply -auto-approve
  aws-s3:
    executor: terraform-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd ~/project/s3
            terraform init -input=false
            terraform apply -auto-approve
  aws-eks:
    executor: terraform-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd ~/project/eks
            terraform init -input=false
            terraform apply -auto-approve
  aws-es:
    executor: terraform-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            cd ~/project/elasticsearch
            terraform init -input=false
            terraform apply -auto-approve

workflows:
  demo-pipeline:
    jobs:
      - start-workflow:
          name: start-workflow
      - demo-vpc:
          name: demo-vpc
          requires:
            - demo-vpc
      - demo-s3:
          name: demo-s3
          requires:
            - demo-vpc
      - demo-efs:
          name: demo-efs
          requires:
            - demo-vpc
      - demo-eks:
          name: demo-eks
          requires:
            - demo-vpc
      - demo-es:
          name: demo-es
          requires:
            - demo-vpc